Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/**/*
    - log/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - config/initializers/devise.rb
