default: &default
  adapter:  postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: exchange_dev
  username: alexander
  port: 5432

test:
  <<: *default
  database: exchange_test
  username: alexander
  port: 5432
